import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { api } from '@/services/api'
import type { InterviewDetail } from '@/types/evaluation'
import { Button } from '@/components/ui/Button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card'
import { ScoreRing } from '@/components/ui/ScoreRing'
import { PageTransition } from '@/components/PageTransition'
import { Skeleton } from '@/components/ui/Skeleton'
import { ArrowLeft, Download, CheckCircle, AlertTriangle, Shield, ShieldAlert, Camera, Copy, Mail, Check } from 'lucide-react'

function ScoreBar({ score, maxScore }: { score: number; maxScore: number }) {
  const pct = (score / maxScore) * 100
  const color = score >= 7 ? 'bg-emerald-500' : score >= 5 ? 'bg-amber-500' : 'bg-red-500'
  return (
    <div className="h-1.5 w-full rounded-full bg-slate-100">
      <div
        className={`h-1.5 rounded-full transition-all duration-1000 ease-out ${color}`}
        style={{ width: `${pct}%` }}
      />
    </div>
  )
}

function buildEmailSummary(interview: InterviewDetail): string {
  const evaluation = interview.score
  if (!evaluation) return ''

  const date = new Date(interview.scheduled_start).toLocaleString('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short',
  })

  const categoryLines = evaluation.categories
    .map((c) => {
      const content = c.contentScore != null ? ` (Content: ${c.contentScore}/4, Delivery: ${c.deliveryScore}/4)` : ''
      return `  - ${c.name}: ${c.score}/${c.maxScore}${content}\n    ${c.comments}${c.evidence ? `\n    Evidence: "${c.evidence}"` : ''}`
    })
    .join('\n')

  const strengths = evaluation.strengths.map((s) => `  + ${s}`).join('\n')
  const weaknesses = evaluation.weaknesses.map((w) => `  - ${w}`).join('\n')
  const followUps = evaluation.followUpAreas?.map((f, i) => `  ${i + 1}. ${f}`).join('\n') || '  None specified'

  return `INTERVIEW SUMMARY — ${interview.candidate_name}
${'='.repeat(50)}

Candidate: ${interview.candidate_name} (${interview.candidate_email})
Position: ${interview.jd_title}
Date: ${date}
Duration: ${interview.duration_minutes} minutes

OVERALL SCORE: ${evaluation.overallRating}/10
RECOMMENDATION: ${evaluation.recommendation}
${evaluation.confidenceLevel ? `CONFIDENCE: ${evaluation.confidenceLevel.toUpperCase()}${evaluation.confidenceReason ? ` — ${evaluation.confidenceReason}` : ''}` : ''}
${evaluation.hintsNeeded ? `HINTS NEEDED: ${evaluation.hintsNeeded}` : ''}

${evaluation.overallComments}

CATEGORY SCORES:
${categoryLines}

STRENGTHS:
${strengths}

AREAS FOR IMPROVEMENT:
${weaknesses}

RECOMMENDED FOLLOW-UP AREAS (for next round):
${followUps}

---
Generated by SkillLens | ${new Date().toLocaleDateString('en-IN')}`
}

export function InterviewResultPage() {
  const { id } = useParams<{ id: string }>()
  const [interview, setInterview] = useState<InterviewDetail | null>(null)
  const [loading, setLoading] = useState(true)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    if (!id) return
    api.get<InterviewDetail>(`/interviews/${id}`)
      .then(setInterview)
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [id])

  if (loading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-8 w-64" />
        <Skeleton className="h-48 w-full rounded-xl" />
        <Skeleton className="h-64 w-full rounded-xl" />
      </div>
    )
  }

  if (!interview) return <p className="text-slate-500">Interview not found.</p>

  const evaluation = interview.score

  return (
    <PageTransition>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center gap-4">
          <Link to="/admin/interviews">
            <Button variant="ghost" size="sm"><ArrowLeft className="h-4 w-4" /> Back</Button>
          </Link>
          <div>
            <h1 className="text-xl font-bold tracking-tight text-slate-900">Interview Results</h1>
            <p className="text-sm text-slate-500">
              {interview.candidate_name} &middot; {interview.jd_title}
            </p>
            <div className="mt-1.5 flex items-center gap-2">
              {interview.persona && (
                <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${
                  interview.persona === 'friendly' ? 'bg-emerald-100 text-emerald-700' :
                  interview.persona === 'tough' ? 'bg-red-100 text-red-700' :
                  'bg-blue-100 text-blue-700'
                }`}>
                  {interview.persona === 'rapid_fire' ? 'Rapid Fire' : interview.persona}
                </span>
              )}
              {interview.adaptive_difficulty && (
                <span className="rounded-full bg-violet-100 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-violet-700">
                  Adaptive ({interview.initial_difficulty})
                </span>
              )}
              {interview.adaptive_difficulty === false && interview.initial_difficulty && (
                <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-slate-600">
                  Fixed: {interview.initial_difficulty}
                </span>
              )}
            </div>
          </div>
        </div>

        {!evaluation ? (
          <Card>
            <CardContent className="py-12 text-center text-slate-500">
              {interview.status === 'completed'
                ? 'Evaluation is being generated. Please refresh in a moment.'
                : `Interview status: ${interview.status}`}
            </CardContent>
          </Card>
        ) : (
          <>
            {/* Overall Score Card */}
            <Card className="overflow-hidden">
              <div className="bg-gradient-to-r from-slate-50 to-indigo-50/30 p-8">
                <div className="flex flex-col items-center gap-6 md:flex-row md:justify-between">
                  <div className="flex items-center gap-8">
                    <ScoreRing score={evaluation.overallRating} maxScore={10} size={140} strokeWidth={10} />
                    <div>
                      <div className="flex items-center gap-3">
                        <div>
                          <p className="text-sm font-medium text-slate-500">Recommendation</p>
                          <p className="mt-1 text-xl font-bold text-slate-900">{evaluation.recommendation}</p>
                        </div>
                        {evaluation.confidenceLevel && (
                          <span className={`mt-5 rounded-full px-2.5 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${
                            evaluation.confidenceLevel === 'high' ? 'bg-emerald-100 text-emerald-700' :
                            evaluation.confidenceLevel === 'medium' ? 'bg-amber-100 text-amber-700' :
                            'bg-red-100 text-red-700'
                          }`}>
                            {evaluation.confidenceLevel} confidence
                          </span>
                        )}
                      </div>
                      <p className="mt-2 max-w-md text-sm text-slate-500 leading-relaxed">{evaluation.overallComments}</p>
                      {evaluation.confidenceReason && (
                        <p className="mt-1 max-w-md text-xs text-slate-400 italic">{evaluation.confidenceReason}</p>
                      )}
                      {evaluation.hintsNeeded != null && evaluation.hintsNeeded > 0 && (
                        <p className="mt-2 text-xs text-amber-600">
                          Interviewer had to simplify/redirect {evaluation.hintsNeeded} time{evaluation.hintsNeeded > 1 ? 's' : ''}
                        </p>
                      )}
                    </div>
                  </div>
                  <div className="flex flex-col gap-2">
                    <Button
                      variant="outline"
                      onClick={() => window.open(`/api/interviews/${id}/report`, '_blank')}
                    >
                      <Download className="h-4 w-4" /> Download PDF
                    </Button>
                    <Button
                      variant="outline"
                      onClick={() => {
                        const summary = buildEmailSummary(interview!)
                        navigator.clipboard.writeText(summary)
                        setCopied(true)
                        setTimeout(() => setCopied(false), 2000)
                      }}
                    >
                      {copied ? <><Check className="h-4 w-4" /> Copied!</> : <><Copy className="h-4 w-4" /> Copy Summary</>}
                    </Button>
                    <Button
                      variant="outline"
                      onClick={() => {
                        const summary = buildEmailSummary(interview!)
                        const subject = `Interview Summary: ${interview!.candidate_name} — ${interview!.jd_title}`
                        window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(summary)}`)
                      }}
                    >
                      <Mail className="h-4 w-4" /> Email Summary
                    </Button>
                  </div>
                </div>
              </div>
            </Card>

            {/* Category Scores */}
            <Card>
              <CardHeader>
                <CardTitle>Category Breakdown</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                  {evaluation.categories.map((cat, i) => (
                    <div
                      key={i}
                      className="rounded-xl border border-slate-100 bg-slate-50/50 p-4 space-y-3 animate-in fade-in slide-in-from-bottom-2"
                      style={{ animationDuration: '400ms', animationDelay: `${300 + i * 100}ms`, animationFillMode: 'both' }}
                    >
                      <div className="flex items-center justify-between">
                        <span className="text-sm font-medium text-slate-700">{cat.name}</span>
                        <span className={`text-lg font-bold ${cat.score >= 7 ? 'text-emerald-600' : cat.score >= 5 ? 'text-amber-600' : 'text-red-600'}`}>
                          {cat.score}/{cat.maxScore}
                        </span>
                      </div>
                      <ScoreBar score={cat.score} maxScore={cat.maxScore} />
                      {(cat.contentScore != null || cat.deliveryScore != null) && (
                        <div className="flex gap-3 text-[10px]">
                          {cat.contentScore != null && (
                            <span className="flex items-center gap-1">
                              <span className="text-slate-400">Content:</span>
                              <span className={`font-bold ${cat.contentScore >= 3 ? 'text-emerald-600' : cat.contentScore >= 2 ? 'text-amber-600' : 'text-red-600'}`}>
                                {cat.contentScore}/4
                              </span>
                            </span>
                          )}
                          {cat.deliveryScore != null && (
                            <span className="flex items-center gap-1">
                              <span className="text-slate-400">Delivery:</span>
                              <span className={`font-bold ${cat.deliveryScore >= 3 ? 'text-emerald-600' : cat.deliveryScore >= 2 ? 'text-amber-600' : 'text-red-600'}`}>
                                {cat.deliveryScore}/4
                              </span>
                            </span>
                          )}
                        </div>
                      )}
                      <p className="text-xs text-slate-500 leading-relaxed">{cat.comments}</p>
                      {cat.evidence && (
                        <p className="text-[11px] text-slate-400 italic border-l-2 border-slate-200 pl-2 leading-relaxed">
                          "{cat.evidence}"
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Strengths & Weaknesses */}
            <div className="grid gap-5 md:grid-cols-2">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-emerald-700">
                    <CheckCircle className="h-5 w-5" /> Strengths
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2.5">
                    {evaluation.strengths.map((s, i) => (
                      <li key={i} className="flex items-start gap-2.5 text-sm text-slate-700">
                        <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-xs font-bold text-emerald-600">+</span>
                        {s}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-amber-700">
                    <AlertTriangle className="h-5 w-5" /> Areas for Improvement
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2.5">
                    {evaluation.weaknesses.map((w, i) => (
                      <li key={i} className="flex items-start gap-2.5 text-sm text-slate-700">
                        <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-amber-100 text-xs font-bold text-amber-600">!</span>
                        {w}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            </div>

            {/* Follow-Up Areas */}
            {evaluation.followUpAreas && evaluation.followUpAreas.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-indigo-700 text-base">
                    <ArrowLeft className="h-4 w-4 rotate-180" /> Recommended Follow-Up Areas
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-xs text-slate-400 mb-3">Topics to explore in the next interview round</p>
                  <ul className="space-y-2">
                    {evaluation.followUpAreas.map((area, i) => (
                      <li key={i} className="flex items-start gap-2.5 text-sm text-slate-700">
                        <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-indigo-100 text-xs font-bold text-indigo-600">{i + 1}</span>
                        {area}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            )}

            {/* Integrity Report */}
            {interview.proctoring_summary && (
              <Card className={
                interview.proctoring_summary.flag === 'high' ? 'border-red-200' :
                interview.proctoring_summary.flag === 'medium' ? 'border-amber-200' : ''
              }>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-base">
                    {interview.proctoring_summary.flag === 'low' ? (
                      <><Shield className="h-5 w-5 text-emerald-600" /> Interview Integrity — No Concerns</>
                    ) : interview.proctoring_summary.flag === 'medium' ? (
                      <><ShieldAlert className="h-5 w-5 text-amber-600" /> Interview Integrity — Some Activity Detected</>
                    ) : (
                      <><ShieldAlert className="h-5 w-5 text-red-600" /> Interview Integrity — Suspicious Activity</>
                    )}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4 sm:grid-cols-4 mb-4">
                    <div className="rounded-lg bg-slate-50 p-3 text-center">
                      <p className={`text-2xl font-bold ${interview.proctoring_summary.tabSwitches > 3 ? 'text-red-600' : 'text-slate-900'}`}>
                        {interview.proctoring_summary.tabSwitches}
                      </p>
                      <p className="text-[10px] text-slate-500 uppercase tracking-wider">Tab Switches</p>
                    </div>
                    <div className="rounded-lg bg-slate-50 p-3 text-center">
                      <p className={`text-2xl font-bold ${interview.proctoring_summary.fullscreenExits > 2 ? 'text-amber-600' : 'text-slate-900'}`}>
                        {interview.proctoring_summary.fullscreenExits}
                      </p>
                      <p className="text-[10px] text-slate-500 uppercase tracking-wider">Fullscreen Exits</p>
                    </div>
                    <div className="rounded-lg bg-slate-50 p-3 text-center">
                      <p className={`text-2xl font-bold ${interview.proctoring_summary.devtoolsOpens > 0 ? 'text-red-600' : 'text-slate-900'}`}>
                        {interview.proctoring_summary.devtoolsOpens}
                      </p>
                      <p className="text-[10px] text-slate-500 uppercase tracking-wider">DevTools Opens</p>
                    </div>
                    <div className="rounded-lg bg-slate-50 p-3 text-center">
                      <p className="text-2xl font-bold text-slate-900">{interview.proctoring_summary.snapshotCount}</p>
                      <p className="text-[10px] text-slate-500 uppercase tracking-wider">Photos Captured</p>
                    </div>
                  </div>

                  {/* Snapshot Gallery */}
                  {interview.snapshots && interview.snapshots.length > 0 && (
                    <div>
                      <p className="mb-2 flex items-center gap-1.5 text-xs font-medium text-slate-500">
                        <Camera className="h-3.5 w-3.5" /> Candidate Photos
                      </p>
                      <div className="flex gap-2 overflow-x-auto pb-2">
                        {interview.snapshots.map((img, i) => (
                          <img
                            key={i}
                            src={img}
                            alt={`Snapshot ${i + 1}`}
                            className="h-24 w-32 rounded-lg object-cover border border-slate-200 shrink-0 cursor-pointer hover:ring-2 hover:ring-primary transition-all"
                            onClick={() => window.open(img, '_blank')}
                          />
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Proctoring Event Timeline */}
                  {interview.proctoring_events && interview.proctoring_events.length > 0 && (
                    <details className="mt-3">
                      <summary className="text-xs font-medium text-slate-400 cursor-pointer hover:text-slate-600">
                        View event timeline ({interview.proctoring_events.filter((e) => e.type !== 'snapshot').length} events)
                      </summary>
                      <div className="mt-2 max-h-[200px] overflow-y-auto space-y-1">
                        {interview.proctoring_events.filter((e) => e.type !== 'snapshot').map((evt, i) => (
                          <div key={i} className="flex items-center gap-2 text-xs text-slate-500">
                            <span className="text-[10px] font-mono text-slate-400 w-20 shrink-0">
                              {new Date(evt.timestamp).toLocaleTimeString('en-IN', { timeStyle: 'medium' })}
                            </span>
                            <span className={`rounded px-1.5 py-0.5 text-[10px] font-medium ${
                              evt.type === 'tab_switch' ? 'bg-amber-100 text-amber-700' :
                              evt.type === 'tab_return' ? 'bg-emerald-100 text-emerald-700' :
                              evt.type === 'fullscreen_exit' ? 'bg-blue-100 text-blue-700' :
                              'bg-red-100 text-red-700'
                            }`}>
                              {evt.type.replace('_', ' ')}
                            </span>
                          </div>
                        ))}
                      </div>
                    </details>
                  )}
                </CardContent>
              </Card>
            )}

            {/* Interview Replay with Highlights */}
            {interview.transcript && interview.transcript.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle>Interview Replay</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="max-h-[500px] space-y-3 overflow-y-auto pr-2">
                    {interview.transcript.map((entry, i) => {
                      const highlight = evaluation.highlights?.find((h) => h.exchangeIndex === i)
                      const borderColor = highlight
                        ? highlight.type === 'strong' ? 'border-l-emerald-500'
                          : highlight.type === 'weak' ? 'border-l-amber-500'
                          : 'border-l-red-500'
                        : ''

                      return (
                        <div key={i}>
                          <div className={`flex ${entry.role === 'USER' ? 'justify-end' : 'justify-start'}`}>
                            <div className={`max-w-[80%] rounded-xl px-4 py-2.5 text-sm ${
                              entry.role === 'USER'
                                ? `bg-primary/10 text-slate-800 ${highlight ? `border-l-4 ${borderColor}` : ''}`
                                : 'bg-slate-100 text-slate-700'
                            }`}>
                              <p className="mb-0.5 text-[10px] font-semibold uppercase tracking-wider text-slate-400">
                                {entry.role === 'USER' ? interview.candidate_name : 'Interviewer'}
                              </p>
                              <p className="whitespace-pre-wrap leading-relaxed">{entry.text}</p>
                            </div>
                          </div>
                          {highlight && (
                            <div className={`ml-4 mt-1 flex items-start gap-1.5 text-xs ${
                              highlight.type === 'strong' ? 'text-emerald-600'
                                : highlight.type === 'weak' ? 'text-amber-600'
                                : 'text-red-600'
                            }`}>
                              <span className="mt-0.5">
                                {highlight.type === 'strong' ? '●' : highlight.type === 'weak' ? '▲' : '◆'}
                              </span>
                              <span>{highlight.note}</span>
                            </div>
                          )}
                        </div>
                      )
                    })}
                  </div>

                  {/* Highlight Legend */}
                  {evaluation.highlights && evaluation.highlights.length > 0 && (
                    <div className="mt-4 flex gap-4 border-t border-slate-100 pt-3">
                      <span className="flex items-center gap-1.5 text-[10px] text-emerald-600"><span>●</span> Strong answer</span>
                      <span className="flex items-center gap-1.5 text-[10px] text-amber-600"><span>▲</span> Needs improvement</span>
                      <span className="flex items-center gap-1.5 text-[10px] text-red-600"><span>◆</span> Red flag</span>
                    </div>
                  )}
                </CardContent>
              </Card>
            )}
          </>
        )}
      </div>
    </PageTransition>
  )
}
